project:
  type: website
  output-dir: docs

website:
  title: "PM 566 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: PM 566 Final Project Written Report.qmd
        text: Full Report
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



